---
title: "May 30, 2023"
author: Anthony Pompetti
cache: true
format: 
  revealjs:
    theme: simple
    logo: ../Coriell_Logo.png
    df-print: paged
    embed-resources: true
---

```{r setup, echo=FALSE, include=FALSE, cache=TRUE, cache.lazy=FALSE}
library(glmnet)
library(caret)
source(here::here("scripts", "01_data_preprocessing.R"))
se <- HDF5Array::loadHDF5SummarizedExperiment(dir = here("results","h5","rrbs_gfwt"), prefix = "update")
age_sites <- readRDS(here("results/rds/age_sites.rds"))

#filter for colon samples
se <- se[,se$organ == "COL" & se$microbiome %in% c("gf", "wt")]

#filter for aging sites
se <- subsetByOverlaps(se, age_sites)

#filter for coverage/variance
se <- filter_rrbs(se, nblocks = 20, cores = 40, cpg_select = "cgi", progressbar = FALSE)

#realize meth matrix
meth <- getMeth(se, type = "raw")
meth <- realize_Parallel(meth, cores = 6, nblocks = 3)
meth <- meth[!matrixStats::rowAnyNAs(meth),]

#get only the wt samples 
meth_wt <- t(meth[,se$microbiome == "wt"])
#get only the gf samples
meth_gf <- t(meth[,se$microbiome == "gf"])

age_wt <- colData(se[,se$microbiome == "wt"])$age
age_gf <- colData(se[,se$microbiome == "gf"])$age
```

```{r wt_fit, echo=FALSE, include=FALSE}
set.seed(123)
lambda_seq <- 10^seq(2, -2, by = -.1)
#fit on wt
fit_wt <- glmnet::cv.glmnet(meth_wt, age_wt, alpha = 0)

#predict on wt
age_pred_wt.wt <- predict(fit_wt, newx = meth_wt, s = fit_wt$lambda.min) %>% as.double()
age_pred_gf.wt <- predict(fit_wt, newx = meth_gf, s = fit_wt$lambda.min) %>% as.double()

#create dataframe with wt preds
pred_wt.wt <- data.frame(actual = age_wt, pred = age_pred_wt.wt, microbiome = "wt", row.names = rownames(meth_wt))
pred_gf.wt <- data.frame(actual = age_gf, pred = age_pred_gf.wt, microbiome = "gf", row.names = rownames(meth_gf))

#rbind rows
pred.wt <- rbind(pred_wt.wt, pred_gf.wt)

#plot predictions from wt fit
p.wt <- ggplot(data = pred.wt, mapping = aes(x = actual, y = pred, color = microbiome, customdata = rownames(pred))) +
  geom_point() +
  labs(x = "Actual Age", y = "Predicted Age", title = "Ridge Regression: Actual vs Predicted Age") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") + 
  geom_smooth(method = lm)
```

```{r plot_wt_fit, echo=FALSE}
ggplotly(p.wt)
```

```{r gf_fit, echo=FALSE, include=FALSE}
#fit on gf
fit_gf <- glmnet::cv.glmnet(meth_gf, age_gf, alpha = 0)

#predict on gf
age_pred_wt.gf <- predict(fit_gf, newx = meth_wt, s = fit_gf$lambda.min) %>% as.double()
age_pred_gf.gf <- predict(fit_gf, newx = meth_gf, s = fit_gf$lambda.min) %>% as.double()

#create dataframe with gf preds
pred_wt.gf <- data.frame(actual = age_wt, pred = age_pred_wt.gf, microbiome = "wt", row.names = rownames(meth_wt))
pred_gf.gf <- data.frame(actual = age_gf, pred = age_pred_gf.gf, microbiome = "gf", row.names = rownames(meth_gf))

#rbind rows
pred.gf <- rbind(pred_wt.gf, pred_gf.gf)

#plot predictions from gf fit
p.gf <- ggplot(data = pred.gf, mapping = aes(x = actual, y = pred, color = microbiome, customdata = rownames(pred))) +
  geom_point() +
  labs(x = "Actual Age", y = "Predicted Age", title = "Ridge Regression: Actual vs Predicted Age") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") + 
  geom_smooth(method = lm)
```

```{r plot_gf_fit, echo=FALSE}
ggplotly(p.gf)
```